aubo_i5:
  # publish all joint states--------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Gazebo use controller that ros_control(joint_position_controller)
  # Position Controllers------------------
  shoulder_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint
    pid: { p: 1000,  i: 0, d: 100, i_clamp: 100 }

  upperArm_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: upperArm_joint
    pid: { p: 1000,  i: 0, d: 100, i_clamp: 100 }

  foreArm_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: foreArm_joint
    pid: { p: 1000,  i: 0, d: 100, i_clamp: 100 }

  wrist1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist1_joint
    pid: { p: 1000,  i: 0, d: 100, i_clamp: 100 }

  wrist2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist2_joint
    pid: { p: 1000,  i: 0, d: 100, i_clamp: 100 }

  wrist3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist3_joint
    pid: { p: 1000,  i: 0, d: 100, i_clamp: 100 }
