controller_list:
  - name: aubo_i5
    action_ns: joint_trajectory
    type: JointTrajectory
    default: true
    joints:
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
