aubo:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      aubo_controller:
        type: position_controllers/JointTrajectoryController
        joints:
          - shoulder_joint
          - upperarm_joint
          - forearm_joint
          - wrist1_joint
          - wrist2_joint
          - wrist3_joint
