#################
## Controllers ##
#################

aubo_i3:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    arm_controller:
      type: position_controllers/JointTrajectoryController
      action_monitor_rate: 200
      joints:
        - shoulder_joint
        - upperArm_joint
        - foreArm_joint
        - wrist1_joint
        - wrist2_joint
        - wrist3_joint
      stop_trajectory_duration: 1.0

aubo_i5:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    arm_controller:
      type: position_controllers/JointTrajectoryController
      action_monitor_rate: 200
      joints:
        - shoulder_joint
        - upperArm_joint
        - foreArm_joint
        - wrist1_joint
        - wrist2_joint
        - wrist3_joint
      constraints:
        shoulder_joint: { goal: 0.02, trajectory: 0.04 }
        upperArm_joint: { goal: 0.02, trajectory: 0.04 }
        foreArm_joint: { goal: 0.02, trajectory: 0.04 }
        wrist1_joint: { goal: 0.02, trajectory: 0.04 }
        wrist2_joint: { goal: 0.02, trajectory: 0.04 }
        wrist3_joint: { goal: 0.02, trajectory: 0.04 }
      stop_trajectory_duration: 1.0

aubo_i7:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    arm_controller:
      action_monitor_rate: 200
      type: position_controllers/JointTrajectoryController
      joints:
        - shoulder_joint
        - upperArm_joint
        - foreArm_joint
        - wrist1_joint
        - wrist2_joint
        - wrist3_joint
      stop_trajectory_duration: 1.0
